version: '3.21'

services:
  postgres:
    image: postgres:11.6-alpine
    container_name: ${POSTGRES_CONTAINER}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./pg_data:/var/lib/postgresql
    networks:
      guarani-network:
        aliases: 
          - postgres

  php-apache-server:
    container_name: ${APACHE_CONTAINER}
    build:
      dockerfile: Dockerfile-php-apache
    volumes:
      - ./guarani:/usr/local/proyectos/guarani
      - ./g3w3:/usr/local/proyectos/g3w3
      - ./config/sites-available/toba_3_3.conf:/etc/apache2/sites-available/toba_3_3.conf
      - ./config/sites-available/alias.conf:/etc/apache2/sites-available/alias.conf
      - ./config/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8081:8081
      - 80:80
    links:
      - postgres:postgres
    networks:
      guarani-network:
        aliases:
          - php-apache

networks:
  guarani-network:
    name: guarani-net
    driver: bridge
    ipam:
      driver: default